version: '3'

services:
 django:
  container_name: django_rest
  image: django_rest:1.0
  environment:
    - DJANGO_DEBUG=true
  volumes:
    - ./code:/code
  ports:
    - "8000:8000"
  tty: true
  command: python3 ./rest/manage.py runserver 0:8000
